name: prohelp_app
description: A new Flutter project by Stanley Nyekpeye.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2


environment:
  sdk: ">=2.16.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:    
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  money_formatter: ^0.0.3
  fluttertoast: ^8.1.1
  get: ^4.6.5
  shimmer: ^2.0.0
  flutter_svg: ^0.23.0
  page_transition: ^2.0.9
  loading_overlay_pro: ^2.1.1
  shared_preferences: ^2.0.15
  persistent_bottom_nav_bar: ^4.0.2
  http_interceptor: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  pinch_zoom: ^1.0.0
  country_code_picker: ^2.0.2
  sms_autofill: ^2.2.0
  pin_code_fields: ^7.4.0
  uuid: ^3.0.6
  url_launcher: ^6.0.20
  # confetti: ^0.6.0
  # flutter_html: ^2.2.1
  image_picker: ^0.8.4
  image_cropper: ^3.0.1
  # flutter_paystack: ^1.0.7
  flutter_countdown_timer: ^4.1.0
  flutter_time_picker_spinner: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  top_snackbar_flutter: ^3.0.0+1
  flutter_cupertino_date_picker_fork: ^1.0.7
  sliding_up_panel: ^2.0.0+1
  easy_stepper: ^0.5.0
  flutter_rating_bar: ^4.0.1
  timeago: ^3.2.2
  file_picker: ^5.2.8
  http: ^0.13.5
  substring_highlight: ^1.0.33
  syncfusion_flutter_sliders: ^21.2.3
  sqflite: ^2.2.8
  socket_io_client: ^2.0.2
  audioplayers: ^1.0.1
  flutter_downloader: ^1.10.4
  currency_text_input_formatter: ^2.1.7
  flutter_staggered_grid_view: ^0.6.2
  pay_with_paystack: ^1.0.3
  carousel_slider: ^4.2.1
  # flutter_localization: ^0.17.0

  firebase_core_platform_interface: 4.8.0

  firebase_analytics: 10.4.2
  firebase_auth: ^4.6.2
  firebase_core: 2.13.1
  firebase_crashlytics: 3.2.0
  firebase_performance: 0.9.2+2
  google_sign_in: ^6.1.0

  # cloud_functions: ^3.2.8
  firebase_storage: ^11.1.0
  firebase_messaging: ^14.0.0
  path_provider: ^2.0.15
  connectivity_plus: ^2.1.0

dependency_overrides:
  # firebase_core_platform_interface: 4.5.1
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    #         style: italic
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
        - asset: assets/fonts/PTSerif-Bold.ttf
  #         weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
